"""
Used for translation.
# ToDo: Use a standard python way.
"""
import pandas as pd

translator_lst = [{"EN": "Demo Robot Plant", "DE": "Demonstrator Roboterfabrik"},
                  {"EN": "AGV", "DE": "FTF"},
                  {"EN": "Bending Station", "DE": "Biegestation"},
                  {"EN": "Warehouse", "DE": "Lager"},
                  {"EN": "Storage Place", "DE": "Lagerplatz"},
                  {"EN": "Raw Material", "DE": "Rohmaterial"},
                  {"EN": "Box", "DE": "Box"},
                  {"EN": "Small Box", "DE": "Kleine Box"},
                  {"EN": "Medium Box", "DE": "Mittlere Box"},
                  {"EN": "Big Box", "DE": "Große Box"},
                  {"EN": "Raw Material Robot", "DE": "Rohmaterial FTF"},
                  {"EN": "Finished Goods Robot", "DE": "Fertigteil FTF"},
                  {"EN": "Raw Material Buffer", "DE": "Rohmaterial Puffer"},
                  {"EN": "Finished Goods Buffer (small)", "DE": "Fertigteil (kleine Box)"},
                  {"EN": "Finished Goods Buffer (medium)", "DE": "Fertigteil (mittlere Box)"},
                  {"EN": "Finished Goods Buffer (big)", "DE": "Fertigteil (große Box)"},
                  {"EN": "Bending Station 1", "DE": "Biegestation 1"},
                  {"EN": "Main Warehouse", "DE": "Hauptlager"},
                  {"EN": "Raw Material Storage", "DE": "Rohmaterial Lager"},
                  {"EN": "Finished Goods Storage (small)", "DE": "Fertigteil Lager (kleine Box)"},
                  {"EN": "Finished Goods Storage (medium)", "DE": "Fertigteil Lager (mittlere Box)"},
                  {"EN": "Finished Goods Storage (big)", "DE": "Fertigteil Lager (große Box)"},
                  {"EN": "Box Finished Product", "DE": "Fertigprodukt Box"},
                  {"EN": "Small Box", "DE":  "Kleine Box"},
                  {"EN": "Medium Box", "DE": "Mittlere Box"},
                  {"EN": "Big Box", "DE": "Große Box"},
                  {"EN": "Loading Raw Material", "DE": "Rohmaterial aufladen"},
                  {"EN": "Transporting Raw Material", "DE": "Rohmaterial transportieren"},
                  {"EN": "Unloading Raw Material", "DE": "Rohmaterial abladen"},
                  {"EN": "Loading Finished Product", "DE": "Fertigteil aufladen"},
                  {"EN": "Transport Finished Product", "DE": "Fertigteil transportieren"},
                  {"EN": "Unloading Finished Product", "DE": "Fertigteil abladen"},
                  {"EN": "Deliver Finished Product to the customer", "DE": "Auslieferung Fertigprodukt"},
                  {"EN": "Raw Material Transport Process", "DE": "Transport Prozess Rohmaterial"},
                  {"EN": "Small Box Transport Process", "DE": "Transport Prozess (Kleine Box)"},
                  {"EN": "Medium Box Transport Process", "DE": "Transport Prozess (Mittlere Box)"},
                  {"EN": "Big Box Transport Process", "DE": "Transport Prozess (Große Box)"},
                  {"EN": "Small Box Bending Process", "DE": "Biege Prozess (Kleine Box)"},
                  {"EN": "Medium Box Bending Process", "DE": "Biege Prozess (Mittlere Box)"},
                  {"EN": "Big Box Bending Process", "DE": "Biege Prozess (Große Box)"},
                  {"EN": "Small Box Rework Process", "DE": "Nacharbeit Prozess (Kleine Box)"},
                  {"EN": "Medium Box Rework Process", "DE": "Nacharbeit Prozess (Mittlere Box)"},
                  {"EN": "Big Box Rework Process", "DE": "Nacharbeit Prozess (Große Box)"},
                  {"EN": "Loading Process Warehouse", "DE": "Lade Prozess Lager"},
                  {"EN": "Small Box Unloading Process Warehouse", "DE": "Ablade Prozess Lager (Kleine Box)"},
                  {"EN": "Medium Box Unloading Process Warehouse", "DE": "Ablade Prozess Lager (Mittlere Box)"},
                  {"EN": "Big Box Unloading Process Warehouse", "DE": "Ablade Prozess Lager (Große Box)"},
                  {"EN": "Loading Process Production", "DE": "Lade Prozess Produktion"},
                  {"EN": "Small Box Unloading Process Production", "DE": "Lade Prozess Produktion (Kleine Box)"},
                  {"EN": "Medium Box Unloading Process Production", "DE": "Lade Prozess Produktion (Mittlere Box)"},
                  {"EN": "Big Box Unloading Process Production", "DE": "Lade Prozess Produktion (Große Box)"},
                  {"EN": "Small Box Customer Delivery Process", "DE": "Auslieferung Prozess (Kleine Box)"},
                  {"EN": "Medium Box Customer Delivery Process", "DE": "Auslieferung Prozess (Mittlere Box)"},
                  {"EN": "Big Box Customer Delivery Process", "DE": "Auslieferung Prozess (Große Box)"},
                  {"EN": "Goods Receipt Process", "DE": "Wareneingangsprozess"}]

translator_df = pd.DataFrame(translator_lst)
