#
# This is a docker-compose file for starting the servies.
#

version: '3.5'
services:
  dashboard:
    build:
      context: Dashboard-UI
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"

  openfire:
    image: nasqueron/openfire:latest
    ports:
      - "9090:9090"
      - "5222:5222"
      - "7777:7777"
    volumes:
      - /C/Users/YOUR/PATH/Openfire:/var/lib/openfire